spring:
  application:
    name: ani-rss-application
  web:
    resources:
      static-locations: classpath:/META-INF/dist
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
      enabled: true
  jmx:
    enabled: false
server:
  port: 7789
  address: 0.0.0.0

springdoc:
  swagger-ui:
    enabled: true
  allowed-locales: 127.0.0.1
  api-docs:
    enabled: true